### ISSUE TITLE
Feature request: Argument / flag whitelist should be used for autocomplete suggestions

### ISSUE THREAD

**Issue by ndepal** [DannyBen/bashly#133]
When specifying a whitelist for an argument or a flag with the `allowed` field, it would be nice if those values would be used as the autocomplete suggestions automatically, without having to repeat those options in the `completions`.

E.g. today I have to write
```
commands:
- name: upload
  help: Upload a file
  allowed: [foo, bar]
  completions:
  - foo
  - bar
```

It would be easy to have the same behavior when just writing
```
commands:
- name: upload
  help: Upload a file
  allowed: [foo, bar]
```
