### ISSUE TITLE
Subcommand with short code and no args does not work

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#16]
With this YAML file:

```yaml
name: rush
help: Personal package manager
version: 0.1.0

commands:
- name: config
  short: c
  help: Show the configuration file

- name: get
  short: g
  help: Install a package

  args:
  - name: repo
    required: true
    help: Repository name
  - name: package
    required: true
    help: Package name
```

This does not work:

```
$ ./rush c
````

While this, works:

```
$ ./rush g
````
