### ISSUE TITLE
Can't use flags

### ISSUE THREAD

**Issue by insign** [DannyBen/bashly#167]
Don't know why, but the generated file are not accepting flags.

```shell
./ben dns abc.com --rounds=1
# invalid argument: 1

./ben dns abc.com --rounds 1
# invalid argument: 1

./ben dns abc.com --rounds="1"
# invalid argument: 1
```

Here a snapshot to let you investigate the [bashly.yml](https://github.com/insign/ben/blob/24a0eade7d63cde127d9d7463c80d30b0f638471/src/bashly.yml)

https://github.com/insign/ben/tree/24a0eade7d63cde127d9d7463c80d30b0f638471

P.S.: Doesn't work in both bash and zsh.

**Comment by DannyBen** [comment]
You must tell bashly if your flag requires an argument by adding the `arg` option.

You can read more about it [here](https://bashly.dannyb.co/configuration/flag/#arg) or see an example usage [here](https://github.com/DannyBen/bashly/tree/master/examples/commands#readme).

I believe this YAML snippet below works as you intended:

```yaml
flags:
# ...
- long: --rounds
  arg: count # added this
  default: "3"
  help: How many times repeat the test before choose a winner
- long: --sleep
  arg: seconds  # added this
  help: How many secods to wait beetween rounds
  default: 1s
# ...
```
