### ISSUE TITLE
Cannot generate completion when using split configs

### ISSUE THREAD

**Issue by surgiie** [DannyBen/bashly#177]
Hello again, 

Im not sure if im misconfiguring this on my end but it appears like completion generation is not working when using split configs:

```yaml
name: mycli
commands:
- import: src/configs/example.yml
```
The split config has a name defined

```yaml
name: example
short: e
help: Example command.
```

but when I tried to run `bashly add comp script` generates the following error is thrown:

```bash
Bashly::ConfigurationError
root.commands[0].name must be a string
```

I have confirmed that completion works as expected when the command config is defined in the `bashly.yml` file but it appears when using `import` the yaml data is not being recognized?
