### ISSUE TITLE
Unable to use YAML aliases in config file (Ruby 3.1)

### ISSUE THREAD

**Issue by dhruvmanila** [DannyBen/bashly#185]
* Ruby version: `ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]`
* Bashly version: `0.7.6`

There's an error when generating from a config file containing YAML aliases:

```
$ BASHLY_TARGET_DIR=/Users/dhruv/dotfiles/bin bashly generate
creating user files in src
Psych::BadAlias
Unknown alias: upgrade_package_list
```

### Config file

```yaml
...
    args:
      - name: package
        help: package to upgrade
        default: all
        allowed: &upgrade_package_list
          - # ... list of packages

    completions: *upgrade_package_list
...
```

**Comment by DannyBen** [comment]
I am unable to reproduce this, but I remember seeing this in other (non bashly) contexts.

This file works for me as is:

```yaml
name: cli

args:
- name: package
  help: package to upgrade
  default: all
  allowed: &upgrade_package_list
  - all
  - only-one

completions: *upgrade_package_list
```

I am assuming you are using the ruby and not the docker version rigtht?

If so, my guess is that it is something to do with the `psych` gem installation - perhaps your default version is older than the latest version you have installed.

Can you paste the output of `gem list psych`?
