### ISSUE TITLE
Repeatable only shows the values of the last flag

### ISSUE THREAD

**Issue by nsainaney** [DannyBen/bashly#186]
I'm running the example https://github.com/DannyBen/bashly/tree/master/examples/repeatable, My code is as follows:

```yaml
- name: try
  flags:
  - long: --data
    short: -d
    arg: data
    help: Provide data values
    required: true

    # Setting this to true on a flag with an argument means the user can type it
    # multiple times, like --data a --data b.
    # The argument will be received as a quoted and space-delimited string which
    # needs to be converted to an array with `eval "data=(${args[--data]})"`
    repeatable: true

  - long: --verbose
    short: -v
    help: Set verbosity level

    # Setting this to true on a regular flag means the user can type it multiple
    # times, in the form of -vvv or -v -v -v.
    # The argument's value will hold the number of times it was entered.
    repeatable: true

  examples:
    - download -d one -d "two three" -vvv
```

Script is copy-pasted from the example:

```bash
# Convert the space delimited string to an array
eval "data=(${args[--data]})"

echo "Data elements:"
for i in "${data[@]}"; do
  echo "$i"
done

# The --verbose arg will contain the number of times it was used by the user
verbose=${args[--verbose]}
echo ""
echo "Verbosity level: $verbose"
echo ""

inspect_args
```

The test run shows:

```
cli try -d one -d "two three" -vvv
Data elements:
two
three

Verbosity level: 1

args:
- ${args[--data]} = two three
- ${args[--verbose]} = 1
```

Expected to see the following (the **one** is missing above and verbose is 1 not 3)

```
args:
- ${args[--data]} = "one" "two three"
- ${args[--verbose]} = 3
```

**Comment by nsainaney** [comment]
Sorry - I should have been clear. I am not running the example as-is. I have added the "root" command in the sample to an existing command I have created (called cli). I'm quite certain there is some local incompatibility. (see generated download cli here: https://gist.github.com/nsainaney/c7f4e1947b5dd8bfd650650550c020fc)

I created a fresh bashly.yml:

```yaml
name: download
help: Sample application to demonstrate the use of repeatable flags
version: 0.1.0

flags:
- long: --data
  short: -d
  arg: data
  help: Provide data values
  required: true

  # Setting this to true on a flag with an argument means the user can type it
  # multiple times, like --data a --data b.
  # The argument will be received as a quoted and space-delimited string which
  # needs to be converted to an array with `eval "data=(${args[--data]})"`
  repeatable: true

- long: --verbose
  short: -v
  help: Set verbosity level

  # Setting this to true on a regular flag means the user can type it multiple
  # times, in the form of -vvv or -v -v -v.
  # The argument's value will hold the number of times it was entered.
  repeatable: true

examples:
  - download -d one -d "two three" -vvv
```

And once again:

```
download -d one -d "two three" -vvv
Data elements:
two
three

Verbosity level: 1

args:
- ${args[--data]} = two three
- ${args[--verbose]} = 1
 ```
