### ISSUE TITLE
`repeatable` breaks `allowed` validation

### ISSUE THREAD

**Issue by nsainaney** [DannyBen/bashly#187]
bashly --version = 0.7.6
bash --version = GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)
MacOS version 12.1 (Monterey)

In working with the [whitelist](https://github.com/DannyBen/bashly/tree/master/examples/whitelist) example, I made `protocol` repeatable:

```yaml
- long: --protocol
  short: -p
  arg: type
  help: Protocol to connect with
  # Whitelist + default
  allowed: [ftp, ssh, http]
  default: ssh
  repeatable: true.      # <--- added this line
```

The resulting code fails:
```
  if [[ ! ${args[--protocol]} =~ ^(ftp|ssh|http)$ ]]; then
    printf "%s\n" "--protocol must be one of: ftp, ssh, http"
    exit 1
  fi
```

The output is:
```
./login us -u user -p ssh
--protocol must be one of: ftp, ssh, HTTP
```

I believe this is because ` ${args[--protocol]}` now evaluates to `"ssh"` and not `ssh`. Also, I would expect the resulting code to iterate through all the protocols to validate.

This isn't blocking as one can write a custom validator (am trying that next)

Thanks!
