### ISSUE TITLE
Config validation should disallow `catch_all` and repeatable args together

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#208]
Sample YAML

```yaml
name: cli
help: Sample application
version: 0.1.0

catch_all:
  label: catchall
  help: Catch all
  required: true

args:
- name: path
  help: Path to one or more files
  repeatable: true
  required: true
  allowed: [one, two]
```

Undesired output

```
$ ./cli
missing required argument: PATH
usage: cli PATH... CATCHALL...
```
