### ISSUE TITLE
Completions for nested commands with aliases are... incomplete...

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#226]
As discovered by @tiagoposse in https://github.com/DannyBen/bashly/issues/224#issuecomment-1133629803, the completions generated for sub-sub-commands with aliases is not working properly.

This problem only exists in the non released master branch, since the released version does not consider aliases for completion at all.

### Reproduction

With the repo cloned, `mkdir -p dev/src` and put this `bashly.yml` in it:

```yaml
name: cli

commands:
- name: alpha
  alias: a

  commands:
  - name: bravo
    alias: b

    commands:
    - name: charlie
      alias: c
```

Then, at the root of the repo create this `debug.rb file:

```ruby
action :debug do
  config = Bashly::Config.new "dev/src/bashly.yml"
  command = Bashly::Script::Command.new config
  result = command.completion_data
  lp result.keys
  # File.write "dev/completely.yaml", result.to_yaml
end
```

and run `run debug` to test it.

The output will be:

```yaml
---
- cli
- cli alpha
- cli a
- cli alpha bravo
- cli alpha b
- cli alpha bravo charlie
- cli alpha bravo c
```

which clearly does not include all the variation of the "full names" of the commands.
