### ISSUE TITLE
[FEATURE] Option to show all commands/subcommands at once and/or to group/show subcommands at parent command level

### ISSUE THREAD

**Issue by iocron** [DannyBen/bashly#229]
I haven't found such feature in the docs, but it would be awesome to have a option to show all commands & subcommands at once when using the command or help flag (or beeing able to show subcommands at parent command level by settings a option) in the bashly.yml config: 

```
name: sample
version: 0.1.0

commands:
- name: init
- name: server
  showSubCommandsAtParentLevel: true
  commands:
  - name: setup
  - name: update
- name: app
  showSubCommandsAtParentLevel: true
  commands: 
  - name: setup
  - name: update
```

Executing the command could produce something like this: 

```
Usage:
  sample [command] [subcommand]
  sample [command] [subcommand] --help | -h
  sample --version | -v

Commands:
  init        Initialize Project

  server   subcommands: 
  server   setup
  server   update

  app      subcommands: 
  app      setup
  app      update
```
