### ISSUE TITLE
How to access permanent environment variable in ./zshrc or ./bashrc

### ISSUE THREAD

**Issue by zmeers** [DannyBen/bashly#247]
Hi! 

I love the package - it's awesome!
I'm looking to create a CLI that relies on an API key which I've set in my ./zshrc file. I've looked at the environment variable documentation, but I still can't figure out how to get that API key and write it to a .env file. Would you mind explaining how this is done?

For reference, I've set my bashly.yml file to include the following:
```
environment_variables:
- name: api_key
  required: true
  default: API_KEY=$APP_API_KEY
```

And then in an .sh file, I have the following:
```
echo "- API_KEY=${API_KEY}"
```

But the echo returns `"- API_KEY="` and not the actual key. I'm sure I'm doing something wrong -- what is it?

Thank you!

**Comment by DannyBen** [comment]
I am glad you like it.

Well - the `environment_variables` configuraiton in bashly is mainly there for aesthetics purposes - naturally, you can access any environment variable straight from your code even without defining it in your bashly.yml.

The definition in bashly.yml has three purposes:

1. To present the user with nice instructions when they run `your-cli --help`
2. To allow you to set a default in case it is not set - in this case, you just need to use something like this:

```yaml
environment_variables:
- name: api_key
  help: Set your API key
  default: the-value
```

3. To allow you to **make sure it is present** by using the `required` flag:

```yaml
environment_variables:
- name: api_key
  help: Set your API key
  required: true
```

To access it from your script you do not need to do anything special - just do `echo $API_KEY` - as you would normally do from any bash script.

Does this help?
