### ISSUE TITLE
Is there a way to add alias "help" to fixed_flags_filter ?

### ISSUE THREAD

**Issue by niksfirefly** [DannyBen/bashly#261]
Is there a simple way to extend fixed_flags_filter with addidtional alias "help"
so there will be -h --help and help aliases?

regards

**Comment by DannyBen** [comment]
Not as an alias. Adding a `cli help` is actually equivalent to adding a command.
You can easily do it using this `bashly.yml` setup:

```yaml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: help
  help: Show help
```

and after running `bashly g`, you will get the `src/help_command.sh` placeholder - put this content in it:

```bash
long_usage=yes
cli_usage
```

which is exactly what is being called when you run `cli --help`.

Does this work for you?
