### ISSUE TITLE
Only commands can be imported?

### ISSUE THREAD

**Issue by taqtiqa-mark** [DannyBen/bashly#270]
```yaml
$ bashly generate
Bashly::ConfigurationError
root.commands[0].commands[0].args[2] contains invalid options: flags
```

When given

```yaml
name: cli
help: Sample application
version: 0.1.0

environment_variables:
- name: api_key
  help: Set your API key

# flags:
# - long: --force
#   short: -f
#   help: Overwrite existing files

commands:
- name: download
  alias: d
  help: Download a file

  # flags:
  # - long: --thing
  #   short: -t
  #   help: Some thing

  examples:
  - cli download example.com
  - cli download example.com ./output -f

  environment_variables:
  - name: default_target_location
    help: Set the default location to download to

  commands:
  - name: subdownload
    alias: d
    help: sub-Download a file
    args:
    - name: source
      required: true
      help: URL to download from
    - name: target
      help: "Target filename (default: same as source)"

    - import: src/conf/subdownload.yml
```

where ` src/conf/subdownload.yml`

```yaml
    flags:
      - long: --force
        short: -f
        help: Overwrite existing files
```

**Comment by DannyBen** [comment]
No. I thought the error was quite descriptive, was it not? :)

```
root.commands[0].commands[0].args[2] contains invalid options: flags
```

It tells you that the resulting configuration file, had a third element in the args array (`args[2]`) has an option named `flags` which is not a valid option.

Your problem is because you call `import` as another array item.

Instead of this:

```yaml
    args:
    - name: source
      required: true
      help: URL to download from
    - name: target
      help: "Target filename (default: same as source)"

    - import: src/conf/subdownload.yml
```

do this:

```yaml
    args:
    - name: source
      required: true
      help: URL to download from
    - name: target
      help: "Target filename (default: same as source)"

    import: src/conf/subdownload.yml
```

Why: A prefix `-` in YAML means an array item, and `flags` is not an item of `args` but a "sibling" of `args`.
