### ISSUE TITLE
Error when splitting configuration in sub/nested commands

### ISSUE THREAD

**Issue by weierophinney** [DannyBen/bashly#279]
### Description

When defining nested commands, if the nested command is defined via an import statement that references a command script, a new script is generated that strips the command prefix.

### Reproduction steps

I observed the issue with each of the following:

```yaml
# src/bashly.yml
name: cli

commands:
- name: toplevel
  help: "The toplevel command namespace"
  commands:
  - import: src/toplevel_nested_command.sh
```

```yaml
# src/bashly.yml
name: cli

commands:
- name: toplevel
  help: "The toplevel command namespace"
  commands:
  - name: nested
    import: src/toplevel_nested_command.sh
```

Where `src/toplevel_nested_command.sh` reads either:

```bash
name: nested
help: "The nested command"
---
inspect_args
```

or, for the second `bashly.yml` example, I tried also omitting the `name` element:

```bash
help: "The nested command"
---
inspect_args
```

However, that led to a validation error.

### Expected behavior

- No new command script generated
- Running `./cli` would list "toplevel" as the only "command" or subcommand group
- Running `./cli toplevel` would list "nested" as the only subcommand

### Actual behavior

- A new command script, `src/nested_command.sh` was created.
- Running `./cli` lists both the "toplevel" subcommand group **and** a "nested" command.
- Runnig `./cli toplevel` correctly lists "nested" as the only subcommand.

In the case where I defined the subcommand name in the `bashly.yml` file and then imported the rest of the definition from the `src/toplevel_nested_command.sh` file, I received a validation error:

```text
Bashly::ConfigurationError
root.commands[14].name must be a string
```

If I define the entire command metadata _in_ `src/bashly.yml`, it will create `src/toplevel_nested_command.yml` correctly. I'd hoped to move all subcommand definitions into these files, to make them more self-documenting, however.

**Comment by DannyBen** [comment]
I can't reproduce this.
Followed your instructions, and the actual behavior matches the expected.

```yaml
# src/bashly.yml
name: cli

commands:
- name: toplevel
  help: "The toplevel command namespace"
  commands:
  - import: src/toplevel_nested_command.sh
```

```bash
# src/toplevel_nested_command.sh
name: nested
help: "The nested command"
---
inspect_args
```

### Output

```
➜ ./cli
cli

Usage:
  cli COMMAND
  cli [COMMAND] --help | -h
  cli --version | -v

Commands:
  toplevel   The toplevel command namespace


➜ ./cli toplevel
cli toplevel - The toplevel command namespace

Usage:
  cli toplevel COMMAND
  cli toplevel [COMMAND] --help | -h

Commands:
  nested   The nested command

```
