### ISSUE TITLE
Multiple global flags do not work

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#293]
### Description

As discussed in #292, it seems that having more than one global flags do not seem to work as expected.

### Reproduction steps

```yaml
# bashly.yml
name: kube
help: Helps with managing containers deployed with Kubernetes
version: 0.1.0

flags:
  - long: --app
    short: -a
    # arg: app
    # allowed: ['xxx', 'yyy']
    # required: true
    help: Name of application.
  - long: --branch
    short: -b
    # arg: branch
    # required: true
    help: Name of branch

commands:
  - name: ls
```

```
➜ ./kube -a -b ls
invalid option: -b
```

### Expected behavior

Global flags should be accepted with all their allowed properties (`arg`, `required`, `allowed` etc).

### Actual behavior

Only one flag is allowed at input time.
