### ISSUE TITLE
Bad completions generated when global flags are in use

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#296]
Discovered by @rience in https://github.com/DannyBen/bashly/discussions/292#discussioncomment-4251600

---

### Description

When using global flags, they will interfere with bash completions for subsequent commands.

This issue is blocked by https://github.com/DannyBen/completely/issues/37

### Reproduction steps

```yaml
# bashly.yml
name: cli

flags:
- long: --debug

commands:
- name: download

  flags:
  - long: --user
    arg: user
    allowed: [admin, anonymous]
    default: admin
```

then run

```
$ bashly g
$ bashly add comp yaml completely.yaml -f
```

### Actual behavior

This will generate the following `completely.yml`:

```yaml
cli:
- "--debug"
# ... trimmed ...
- download

cli download:
- "--help"
- "--user"
- "-h"

cli download*--user:
- admin
- anonymous
```

which means that the following command completion will fail (because there is *something* between `cli` and `download`):

```
$ cli --debug download --user <tab>
```

as can be indicated by running:

```
$ completely test "cli --debug download --user "
download
```

### Expected behavior

Expecting the `completely.yaml` to also include wildcards where the global flags may be:

```yaml
cli:
- "--debug"
# ... trimmed ...
- download

cli*download:
- "--help"
- "--user"
- "-h"

cli*download*--user:
- admin
- anonymous
```

and then this is expected to output the `--user` completions:

```
$ completely test "cli --debug download --user "
admin
anonymous
```
