### ISSUE TITLE
validations on repeatable arguments are only applied to the first value provided

### ISSUE THREAD

**Issue by natling** [DannyBen/bashly#311]
### Description
when an argument has both `repeatable: true` and a validation function, only the first value provided is actually tested. (repeatable flag arguments do not have this problem.)
### Reproduction steps
```yml
# bashly.yml
name: integers_only
help: all arguments must be integers

args:
- name: number
  repeatable: true
  validate: integer
```
### Actual behavior
```
➜ ./integers_only 5.5 3
validation error in NUMBER:
must be an integer

➜ ./integers_only 3 5.5
args:
- ${args[number]} = "3" "5.5"
```
### Expected behavior
```
➜ ./integers_only 5.5 3
validation error in NUMBER:
must be an integer

➜ ./integers_only 3 5.5
validation error in NUMBER:
must be an integer
```
