### ISSUE TITLE
`catch_all` argument and flag parsing consistent with GNU getopt

### ISSUE THREAD

**Issue by brunk** [DannyBen/bashly#316]
### Description

I have come across a use case related to issue #274, in which parsing the command line like GNU getopt would be helpful.  I want to use bashly to write a wrapper around another CLI tool to which I may wish to pass additional arguments and flags.

For example, I would like the first `--force` flag below to be interpreted by the bashly wrapper `arg-parse`, but everything after the `--` should be passed through to the other CLI tool.

```shell
$ ./arg-parse --force arg1 -- arg2 -a --force
```

My reading of GNU [Standards for Command Line Interfaces](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html) and the `getopt` sample code is that argument parsing should terminate upon seeing a `--`.

Using bashly version 0.9.2, I get the following results:  The `--force` flag is only available in the `args` array.  See below for the configuration of `arg-parse`

```shell
$ ./arg-parse --force arg1 -- arg2 -a --force
args:
- ${args[--force]} = 1
- ${args[source]} = arg1

other_args:
- ${other_args[*]} = -- arg2 -a
- ${other_args[0]} = --
- ${other_args[1]} = arg2
- ${other_args[2]} = -a
```

By adding the line `-- ) shift; other_args+=("$@"); break;;` at line 163, I see the following results.  The latter seems more consistent with GNU getopt. 

```shell
$ ./arg-parse.break_on_dash_dash --force arg1 -- arg2 -a --force
args:
- ${args[--force]} = 1
- ${args[source]} = arg1

other_args:
- ${other_args[*]} = arg2 -a --force
- ${other_args[0]} = arg2
- ${other_args[1]} = -a
- ${other_args[2]} = --force
```

I don't know if GNU getopt behavior is desirable but it would be helpful in this use case.

##### bashly.yml

```yaml
name: arg-parse
help: Test args & flags parsing
version: 0.1.0

catch_all: true

args:
- name: source
  required: true
  help: Source argument

flags:
- long: --force
  short: -f
  help: Force the action

examples:
- arg-parse filename
- arg-parse filename -f
```

##### root_command.sh

```bash
# shellcheck shell=bash
inspect_args
```

##### Change to arg-parse.break_on_dash_dash

```diff
--- arg-parse	2022-12-22 09:11:55.258977018 -0500
+++ arg-parse.break_on_dash_dash	2022-12-22 09:30:37.684330104 -0500
@@ -160,6 +160,8 @@
         shift
         ;;

+      -- ) shift; other_args+=("$@"); break;;
+
       -?*)
         other_args+=("$1")
         shift
```
