### ISSUE TITLE
Bad output when using colour functions on wrapped help text lines

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#328]
### Description

It does not appear that there is a way to easily apply colour in help text, especially that which respects `NO_COLOR`. That is, I could do something like:

```yaml
name: colorhelp
help: |-
  I want to make this $(yellow_bold yellow) that respects NO_COLOR.

  I can only do \e1;33mexplicit yellow\e0m, which both affects wrapping and ignores NO_COLOR.
```

The line wrapping logic should *probably* be modified to ignore invisible characters such as ANSI escape codes. (It should *also* probably handle `A^HB` as one character and treat `^I` specially (8 character default, but that gets *really* complex really fast.)

**Comment by halostatue** [comment]
Huh. This *appears* to be a potential bug instead of an enhancement.

```yaml
name: colorhelp
help: |-
  I want to make this $(yellow_bold yellow).

  However, if my line is very long and will be wrapped, then $(yellow_bold bold at the end) does not work correctly.

version: 0.1.0
```

The output should put `bold at the end` and it should be wrapped, but I see:

```
colorhelp

  I want to make this yellow.

  However, if my line is very long and will be wrapped, then boldn at the end does not work correctly.

Usage:
  colorhelp
  colorhelp --help | -h
  colorhelp --version | -v

Options:
  --help, -h
    Show this help

  --version, -v
    Show version number
```

**Comment by halostatue** [comment]
In my *actual* case, the wrapping worked "correctly", but resulted in null output:

```yaml
name: colorhelp
help: |-
  I want to make this $(yellow_bold yellow).

  # this line simulates the wrapping performed by the line wrapper in my actual case
  However, if my line is very long and will be wrapped, then $(yellow_bold
  bold at the end) does not work correctly.

version: 0.1.0
```
