### ISSUE TITLE
Environment variables group shows even if all are private

### ISSUE THREAD

**Issue by halostatue** [DannyBen/bashly#331]
### Description

`Environment Variables:` header should show only if there are non-private environment variables.

### Reproduction steps

Create a `src/bashly.yml` that looks like this:

```yaml
name: private_env_vars
version: 0.1.0

environment_variables:
  - name: EXAMPLE
    default: ''
    private: true
    help: A help message for EXAMPLE
```

Generate and run long help `bashly generate && ./private_env_vars --help`.

### Actual behavior

```console
$ bashly generate && ./private_env_vars --help
creating user files in src
created src/initialize.sh
created src/root_command.sh
created ./private_env_vars
run ./private_env_vars --help to test your bash script
private_env_vars

Usage:
  all_private COMMAND
  all_private [COMMAND] --help | -h
  all_private --version | -v

Options:
  --help, -h
    Show this help

  --version, -v
    Show version number

Environment Variables:
```

### Expected behavior

```console
$ bashly generate && ./private_env_vars --help
creating user files in src
created src/initialize.sh
created src/root_command.sh
created ./private_env_vars
run ./private_env_vars --help to test your bash script
private_env_vars

Usage:
  all_private COMMAND
  all_private [COMMAND] --help | -h
  all_private --version | -v

Options:
  --help, -h
    Show this help

  --version, -v
    Show version number
```
