### ISSUE TITLE
Questions about environment variables

### ISSUE THREAD

**Issue by dddachui** [DannyBen/bashly#347]
I wonder if bashly supports global variables. Use the shell command to obtain some system parameters, such as the system version marked in/etc/centos-release, and use it as global variables after being intercepted by the command. The examples I see are set strings, and the `default` marked in the example is string type

**Comment by DannyBen** [comment]
You have two options to implement what are describe:

Option 1: Implement it yourself, in the `initialize` function

```bash
# src/initialize.sh
TEST="${TEST:-$(git --version)}"
```

Option 2: Assign a default value using the bash `$(...)` syntax

```yaml
# bashly.yml

environment_variables:
- name: bashly_version
  help: Set your Git version
  default: $(git --version)
```
