### ISSUE TITLE
Compose imported config with additional items

### ISSUE THREAD

**Issue by dabrady** [DannyBen/bashly#349]
### Description

Aloha! I'm attempting to leverage your example pattern of `import`-ing common config in different places within my `bashly.yml`, but am running into a limitation: I have not found a way to compose an `import` statement with additional items within the same data structure. 🤔 

Is this currently possible, and if not, do you think we could make it work? My imagined use-case was going to be something like this, for sharing common flags across namespaces without manually declaring them (though using the YAML anchors technique is decent if verbose workaround):
```yaml
name: cli
commands:
- name: foo
  flags:
  #import: src/common_flags.yml
  - long: --another-flag
  - long: --and-another-one

- name: bar
  flags:
  - long: --nothing-common-here

- name: baz
  flags:
  #import: src/common_flags.yml
  - long: --awesomeness    
```

But here is a minimal walkthrough of the troubles I'm having. Say I define some common flags in its own little snippet file, and then import it at the top-level of my CLI like so:

```yaml
# src/common_flags.yml
- long: --quiet
- long: --json
```

```yaml
name: cli
flags:
  import: src/common_flags.yml
```

All is well:
```sh
➜  bashly validate --verbose
---
name: cli
flags:
- long: "--quiet"
- long: "--json"
---
OK
```

But now let's say I want to compose this array of flags with some additional flags: I can't figure out how, and based on my understanding of what's happening (and my read of [the current implementation](https://github.com/DannyBen/bashly/blob/dae03f7a796e01f43334802b32d5394cb378ead6/lib/bashly/refinements/compose_refinements.rb)) I'm not sure it's (currently) possible.

Doing something like this isn't valid YAML, and that validity check seems to run _before_ the `import` statement is processed:
```yaml
name: cli
flags:
  import: src/common_flags.yml
  - long: --interactive
```
☝🏻 👇🏻 
```sh
➜  bashly validate --verbose
 Psych::SyntaxError
(src/bashly.yml): did not find expected key while parsing a block mapping at line 4 column 3
```

But if we make the `import` statement (which is really just a hash) an element of the `flags` array and thus valid YAML, then it results in a nested list, rather than a flat one, and that's no good.
```yaml
name: cli
flags:
  - import: src/common_flags.yml
  - long: --interactive
```
☝🏻 👇🏻 
```sh
➜  bashly validate --verbose
---
name: cli
flags:
- - long: "--quiet"
  - long: "--json"
- long: "--interactive"
---
 Bashly::ConfigurationError
root.flags[0] must be a hash
```

Modifying the definition of the `common_flags` snippet to be `flags` hash itself instead of a plain array doesn't resolve the issue either, it just adds another layer to the resultant nesting. 😣 It still doesn't appear composable.

**Comment by DannyBen** [comment]
Aloha. I think this was mentioned and discussed somewhere, but I don't remember where or what was the conclusion.
Let me play with it a little, see what can be done.

Thanks for the detailed ticket in the meantime.

**Comment by DannyBen** [comment]
Found where it was discussed: #273

**Comment by DannyBen** [comment]
So, here are some pointers. This is a long one, so strap in.

### YAML must be a valid YAML

As you discuvered, the below is invalid:

```yaml
flags:
  import: src/common_flags.yml
  - long: --debug
```

There are two validations that take place:

1. The YAML itself must be valid before anything else (and the above is not valid YAML).
2. After the YAML is valid, it is loaded to Bashly, which can validate its schema.


### Pre-processing with Kojo

The above syntax requires processing the YAML file as a text file (before using `YAML.load_file`). This is outside the scope of Bashly.

As it happens, I have tool for that, named [Kojo](https://github.com/DannyBen/kojo). With it you can pre-process the bashly.yml file as follows:

```yaml
# bashly_src.yml
name: cli

flags:
  @import common_flags
  - long: --debug
```

```yaml
# common_flags.yml
- long: --json
- long: --quiet
```

```shell
$ kojo file bashly_src.yml
name: cli

flags:
  - long: --json
  - long: --quiet
  - long: --debug
```

If you choose this solution, your "build" step will be something like this:

```shell
$ kojo file src/bashly_src.yml --save src/bashly.yml && bashly generate
```

### Importing individual flags

You can still use bashly's native `import` in a merged context. You just need to merge the individual elements (flags):

```yaml
# bashly.yml
name: cli

flags:
  - import: src/flag_quiet.yml
  - import: src/flag_json.yml
  - long: --debug
```

```yaml
# src/flag_json
long: --json
```

```yaml
# src/flag_quiet
long: --quiet
```

### Global flags

If you have flags that appear in *all* subcommands, you can put them on the root command:

```yaml
# bashly.yml
name: cli

flags:
  - long: --debug

commands:
  - name: download
    flags:
      - long: --json
```

```shell
$ ./cli --debug download --json
args:
- ${args[--debug]} = 1
- ${args[--json]} = 1
```

### Anchors

As you mentioned, using YAML anchors is another way of solving this issue ([example](https://github.com/DannyBen/bashly/tree/master/examples/reusable-flags#reusable-flags-example)). Personally, I find it the  most straight forward.


---

With all these options, I do not feel there is a need to complicate it further.

Don't forget that the bashly.yml is just the skeleton configuration - if it becomes so large that you need to consider alternatives that are not presented here, I suspect the problem lies elsewhere.

Also - I consider the `import` feature, more of a leaf in the implementation, rather than a branch, which means that expanding it further must have an epic reasoning, and a very simple implementation.

I hope one of these options points you in the right direction, and am still open to discuss further.
