### ISSUE TITLE
Add support for required environment variables

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#35]
Can probably be done by allowing an alternative syntax to define environment variables:

```yaml
environment_variables:
  API_KEY:
    help: Your API Key
    required: true
```

Another option, is to normalize the `environment_variables` definition, to be like the others and use a single form for both required or optional:

```yaml
environment_variables:
  - name: api_key   # will be capitalized
    help: Your API Key
    required: true
```
