### ISSUE TITLE
Support storing variable via yaml file

### ISSUE THREAD

**Issue by marcinkuzminski** [DannyBen/bashly#366]
### Description

Here's our use case, we keep certain versions inside the source code of bashly generated script. This is mostly used when we do a self-update call that does downloads new script, and does comparison  on internal changes and components our script is installing.

Similar how version works and it's available globally in the script.

Our workaround is to keep thi in the initialize.sh, but it would be nicer if we bump version and all internal versions of components from yaml file.

my idea was a new section called `variables` that would keep them in it's own namespace so it doesn't get mixed with any other script defined vars.

```
variables:
 - foo: bar
```

What do you think about such feature ?

**Comment by DannyBen** [comment]
BTW - since you mentioned internal components, I am not sure if you are familiar with the [Extensible Scripts](https://bashly.dannyb.co/advanced/extensible-scripts/) feature in bashly, which lets you develop standalone scripts that work together. 

Just wanted to mention it in case it is relevant.

**Comment by DannyBen** [comment]
@marcinkuzminski do you still need help with this / wish to discuss this further?

**Comment by DannyBen** [comment]
I am closing this. If there is any interest in continuing the discussion, we can reopen.

**Comment by DannyBen** [comment]
This is now available in master branch and will be added to the next release.

**Comment by DannyBen** [comment]
Since there was more demand for the `variables` section (#562), this is now available in v1.2.4.

**Comment by marcinkuzminski** [comment]
Thank you for implementing this feature! It will help us greatly.

**Comment by DannyBen** [comment]
Docs: [Configuration / Variable](https://bashly.dannyb.co/configuration/variable/)

**Comment by marcinkuzminski** [comment]
Hi Again :)

I have a question: is there any specific reason the global variables are initialized *after* initialize part? 

Based on what i've seen on generated scripts

```
initialize
run "$@" #<-- here is where globals are initialized
```

We have a bunch of code in initialize script that we want to read from the global variables. This chain of actions makes it unavailable there.

**Comment by DannyBen** [comment]
I totally agree with you that it should be in the initialize, but there is a reason.

See the [variables example](https://github.com/DannyBen/bashly/blob/master/examples/variables/src/bashly.yml).

Variables can be defined for the root command or for subcommands.
When they are defined for subcommands, then the only reasonable place to put them is in the function that runs the command (for example `cli_download_command`).

The root command does not have such a function, so the closest thing is the `run()` function, for consistency.

That said - let me try and change it so that global (root) vars go inside `initialize()`.

I am assuming the reasonable place for them is *before* the user-supplied initialize yes?

**Comment by marcinkuzminski** [comment]
> I am assuming the reasonable place for them is before the user-supplied initialize yes?

Yes i think so, IMO this should be a call of it's own even. Just for example:

```
globals_register #<-- it goes here
users initialize.sh script
run "@"
```

One main reason for that is we do this in globals yaml

```
## Global variables
variables:
- name: rcstack_data
  value:
    ## RC_IMAGE defines the current docker-hub image to pull and bind the installer with.
    rc_image_ver: 5.3.1
    ## STACK VERSIONS, BUMP THEM IF STACK CHANGES SIGNIFICANTLY
    rc_stack_router_ver: 1.0.0
    rc_stack_services_ver: 1.0.0
    rc_stack_rhodecode_ver: 1.0.0
    rc_stack_metrics_ver: 1.0.0
```

Format like that allows easier automated tools to bump versions using grep/sed

Then in initialize we actually make it a single vars available globally

e.g

```
rc_image_ver=${rcstack_data["rc_image_ver"]}
```

and also define some globally available functions that generate for example help docs that re-use the data from `rcstack_data`

Hope that makes it more clear, but i feel having it before user initialize is more flexible

**Comment by DannyBen** [comment]
In the new implementation, the variables appear inside the `initialize()` function but <ins>before</ins> the user initialization script:

```bash
initialize() {
  version="0.1.0"
  long_usage=''
  set -e

  # :command.variables
  # :variable.definition
  build_number=1337   # <= here

  # src/initialize.sh
  # user intialize here
}
```

If I understand you correctly, this is what you hope for right?

As for putting it in a separate function, I do not see the need - unless I missed something.

As for your automated tools, I would like to suggest a cleaner approach:

1. Use the "Split Config" feature, and place the variables in a separate YAML partial (say src/variables.yml)
2. Use a YAML manipulation tool such as `yq` to update that partial directly, in its native form, instead of search-and-replacing with `sed`.

Example:

```yaml
# src/bashly.yml
name: cli
help: Sample application demonstrating the use of variables
version: 0.1.0

import: src/variables.yml
```

```yaml
# src/variables.yml
variables:
- name: build_number
  value: 1337
```

If you want, I can merge the PR to master so you can test the edge version (docker or master branch build).
