### ISSUE TITLE
Flags must have a long form if you specify a default value

### ISSUE THREAD

**Issue by ChipS3t** [DannyBen/bashly#373]
### Bashly Version

Latest Ruby Gem

### Description

Flags must have a long form if you want to specify a default value. If a flag has only a short form, the default value is not set correctly in the Bash associative array and the script throws an error. In the [documentation](https://bashly.dannyb.co/configuration/flag/#default), it states that you can access flag values like `${args[--output]}`. If you specify a flag with only a short form, you can still access it from within your script with something like `{args[-o]}`; however, you cannot specify a default value without an error.

### Contents of bashly.yml

```yaml
name: bashly-test
help: 
version: 0.1.0

flags:
  - short: -t
    # long: --test
    arg: test
    help: An example flag
    default: sphinx
```

### Reproduction Steps

`bashly init --minimal`
Change the `bashly.yml` file to look the the example above
`bashly generate`
`./bashly-test` or `./bashly-test -t bard`

### Actual Behavior

Throws an error similar to: `./bashly-test: line 189: args: bad array subscript`

### Expected Behavior

Output:
```
args:
- ${args[-t]} = sphinx
```
