### ISSUE TITLE
Pass bashly.yml through ERB

### ISSUE THREAD

**Issue by n-rodriguez** [DannyBen/bashly#401]
### Description

So users can generate `allowed` args using some Ruby code. Thank you!

**Comment by DannyBen** [comment]
Good idea. Do you have a sample YAML use case?

**Comment by DannyBen** [comment]
The implementation is ready if you want to try it.
Let me know if it aligned with your use case.

**Comment by n-rodriguez** [comment]
use case:

```yml
commands:
  - name: completions
    help: |-
      Generate bash completions
      Usage: eval "\$(ansible completions)"

  - name: ansible
    help: Ansible related commands
    commands:
      - name: playbook
        help: Run Ansible playbook
        flags:
          - long: --playbook
            short: -p
            arg: playbook
            help: Playbook name
            required: true
            repeatable: false
            allowed:
              <%- Dir['playbooks/**/*.yml'].each do |f| -%>
                <%- _, dir, file = f.split('/') -%>
              - <%= "#{dir}_#{file}".gsub('_', '-').gsub('.yml', '') %>
              <%- end -%>
```
