### ISSUE TITLE
Incorrect result in dependency check

### ISSUE THREAD

**Issue by StephanMeijer** [DannyBen/bashly#413]
### Bashly Version

Latest Ruby Gem

### Description

Version 1.0.8

When using `dependencies:` on macOs, I get "missing dependency incorrectly..

```
bash-5.2$ git -v
git version 2.41.0
bash-5.2$ /path/to/command sub
missing dependency: git
```

### Contents of bashly.yml

```yaml
name: nldoc
help: Workflow executor for NLDOC
version: 0.1.0

commands:
  - name: release
    help: Release project to a specific version

    args:
      - name: version
        required: true
        help: Version to release

    examples:
      - nldoc release 1.2.3

dependencies:
  git:
    command: [git]
```

### Reproduction Steps

I think trying `dependencies` on macOs and installing `bash` using `brew` is the best way to reproduce.

### Actual Behavior

It incorrectly tells me `git` is missing.

### Expected Behavior

It should execute just fine as `git` is not missing.
