### ISSUE TITLE
Allow having arbitrary keys (`x-anything`) in `bashly.yml`

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#426]
### Description

This can be useful for custom renderers, for example to add a `x-manpage-description` string for manpage renderes, and so on.

This should also be included in the JSON schema (cc @EmilySeville7cfg).

I think this should help, but can't seem to place it properly in the schema for it to stop bugging me:

```json
"patternProperties": { "^x-": {} }
```

This bashly.yml should pass schema check:

```yaml
name: docker
x-string: hello
x-hash: { key: value }
x-array: [1, 2]
x-int: 1
x-float: 1.2
x-boolean: yes
x-nil: ~

environment_variables:
- name: rush_config
  x-any: hello

commands:
- name: status
  x-any: hello

  args:
  - name: repo
    x-any: hello

  flags:
  - long: --purge
    x-any: hello

- name: images
  commands:
  - name: ls
    x-any: hello
```
