### ISSUE TITLE
Allowed values of optional flags and arguments fail when  `set -u` mode is set

### ISSUE THREAD

**Issue by chovanecadam** [DannyBen/bashly#445]
### Bashly Version

Latest Ruby Gem

### Description

I have a command with optional arguments and flags. Only some values are allowed and none of the flags or arguments are required. However, when no value is passed, the script fails with `unbound variable` error.

The check for the allowed values is done like this:

```bash
  # :command.whitelist_filter
  if [[ -n ${args['ARG']} ]] && [[ ! ${args['ARG']} =~ ^(a|b)$ ]]; then
    printf "%s\n" "ARG must be one of: a, b" >&2
    exit 1
  fi
  if [[ ${args['--option']} ]] && [[ ! ${args['--option']} =~ ^(a|b)$ ]]; then
    printf "%s\n" "--option must be one of: a, b" >&2
    exit 1
  fi
```

This fails with `unbound variable` error if the argument or the flag are not set:

```
$ ./cli test
./cli: line 298: args['ARG']: unbound variable

$ ./cli test a
./cli: line 302: args['--option']: unbound variable
```

The `:command.whitelist_filter` should use ` [[ -n ${args['arg']:-} ]]` instead of  ` [[ -n ${args['arg']} ]]` to check the default values.

### Contents of bashly.yml

```yaml
name: cli
commands:
  - name: test
    args:
      - name: ARG
        allowed:
          - a
          - b

    flags:
      - long: --option
        arg: OPTION
        allowed:
          - a
          - b
```

### Reproduction Steps

```bash
bashly init
bashly add settings

# set `strict: set -u`
sed -i 's/strict: false/strict: set -u/' settings.yml

# copy over bashly.yml

# generate new script
bashly generate

./cli test
```

### Actual Behavior

```
$ ./cli test
./cli: line 298: args['ARG']: unbound variable
```

### Expected Behavior

No error should be shown, because the argument (or flag) are not required.
