### ISSUE TITLE
Allow default array when repeatable is true

### ISSUE THREAD

**Issue by awattez** [DannyBen/bashly#461]
### Description

I would like to provide an array type default value for an argument that has the `repeatable` functionality set to `true`.

Schema validation is not possible : `Incompatible types. Required: string. Actual: array.`

I don't know if it's possible to provide a table as a string ? Like `"[file1.txt file2.txt]"` or `"file1.txt file2.txt"`. I'm not it will work.

```yaml
commands:
  - name: validate
    help: validate txt file
    args:
      - name: file
        repeatable: true
        unique: true
        help: Specify file
        allowed:
          - file1.txt
          - file2.txt
          - file3.txt
        default:
          - file1.txt
          - file2.txt
```

**Comment by DannyBen** [comment]
Well. You can easily use the default generated command, that comes with `inspect_args` in it, to see how things work.

When the argument is an array (like in `repeatable`), it is provided to your script as a space delimited string.
So, right now, if you wish to also supply a default to it, you can do the same.

```yaml
name: cli
help: Sample application
version: 0.1.0

args:
- name: file
  repeatable: true
  unique: true
  help: Specify file
  allowed:
  - file1.txt
  - file2.txt
  - file3.txt
  default: '\"file1.txt\" \"file2.txt\"'
```
```
$ ./cli
# this file is located in 'src/root_command.sh'
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[file]} = "file1.txt" "file2.txt"


$ ./cli file1.txt file2.txt
# this file is located in 'src/root_command.sh'
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[file]} = "file1.txt" "file2.txt"
```

Although I understand the need, it seems like an odd use case - I have never seen this in any other command line tool.

Are you sure it is the right "interface" for your script? If there is a realistic use case for it, maybe I can add array support to the `default` option (although it will probably have to also verify that when it is in array form, then it must also be `repeatable` - not sure yet if the complexity is justified).
