### ISSUE TITLE
Whitelisted arg with default from environment

### ISSUE THREAD

**Issue by ChristianVind** [DannyBen/bashly#469]
Love the framework :)

What I would like, is for a whitelisted argument (one that uses `allowed` as demonstrated  [here](https://github.com/DannyBen/bashly/tree/master/examples/whitelist#readme)) to have it's default set by an environment variable (if set).

There's a `default` option, but I can't figure out if I could use that to implement what I suggest.

Basically something like:

```
- long: --environment
  short: -e
  arg: env
  help: Chosen environment
  # Whitelist + default environment variable + default 
  allowed: [DEV, TEST, PROD]
  # Maybe like this...
  default_env: ENVIRONMENT
  default: DEV
```

Note sure that the above is the way to specify that, but the end result I'm looking for is this:

`./demo` : option `e` is not set. Neither is `ENVIRONMENT`. The argument of option `e` is the hardcoded value `DEV`.

`ENVIRONMENT=TEST ./demo` : option `e` is not set, but `ENVIRONMENT` is, so that the argument ends up being TEST. Of course that should fail, if the environment variable is set, but not to any of the allowed values.

`ENVIRONMENT=TEST ./demo -e PROD`: option `e` is set to PROD via the command line and that is the value it should take (command line should IMHO take precedence over environment variables)

Does that make any sense? Could it be achieved with the current framework?

**Comment by DannyBen** [comment]
Yes, this can be done.
No, there is no special built in facility for it.

Having both a default and an environment variable override could be confusing. I would consider using one or the other.
But, whatever you decide, this is how I normally do it:

```yaml
# bashly.yml
name: cli

environment_variables:
- name: cli_env
  help: Set environment

flags:
- long: --env
  short: -e
  help: |-
    Set environment.
    Default: The value of CLI_ENV or DEV if empty.
  allowed: [DEV, TEST, PROD]
  arg: Environment name
```

```bash
# src/root_command.sh
env=${args[--env]:-${CLI_ENV:-DEV}}
echo "$env"
```

Of course, in this case, you are not fully enjoying the `allowed` option, since you will have to verify that the environment variable is valid as well. Something like:

```bash
# src/root_command.sh
env=${args[--env]:-$CLI_ENV}
[[ $env =~ ^(DEV|PROD|TEST)$ ]] || env=DEV

echo "[$env]"
```

Keep in mind that you can use `default` on the environment variable as well:

```yaml
environment_variables:
- name: cli_env
  help: Set environment
  default: DEV
```

and then your code becomes simpler:

```bash
env=${args[--env]:-$CLI_ENV}
```

💭 *I wonder if adding `allowed` to `environment_variable` is something worth considering....
This will then be an air-tight solution - no?*

**Comment by ChristianVind** [comment]
Thanks a lot! Very helpful :)
I'll try out your suggestion. I thought that the `allowed` keyword required you to use `default` or the `required` keyword as well. But that might have been an earlier version (or never).

**Comment by DannyBen** [comment]
Sure thing.

I don't recall `allowed` and `required` connected.

a) Let me know if you don't get a satisfactory and intuitive solution. I am open to improving things, and I totally understand the use case at hand - I have it as well.
b) The [documentation](https://bashly.dannyb.co/) is hopefully clear enough - there should be no need to guess how things behave - if there is a special behavior, I am documenting it - so if anything in the docs is not helpful enough, also let me know.

**Comment by ChristianVind** [comment]
I've incorporated your suggestion in my script(s) and it works like a charm. Thanks again :)

In my case I had code in place to do different things depending on the resulting value _AND_ to exit with an error message in case it was gibberish/unsupported.
Still I think that the `environment_variable.allowed` whitelist would be a nice addition (if it's otherwise air-tight) in order to have the framework catch these errors early.

From my point of view the "issue" is closed. And so I hope I'm doing the right thing by clicking the Close as completed...

**Comment by DannyBen** [comment]
I have already added `environment_variable.allowed` in #472.

I will release it either later today or tomorrow.

Then, your YAML can be as simple as:

```yaml
name: cli
help: Sample application
version: 0.1.0

environment_variables:
- name: app_env
  help: Application environment
  default: dev
  allowed: &app_env
  - dev
  - prod
  - test

flags:
- long: --env
  short: -e
  arg: env
  help: Application environment
  allowed: *app_env
```

and in your script:

```bash
env="${args[--env]:-$APP_ENV}"
```
