### ISSUE TITLE
Default argument is not validated

### ISSUE THREAD

**Issue by keilmillerjr** [DannyBen/bashly#492]
### Description

When a default value is used for the argument, it bypasses all validations. This is a problem if you need to validate the contents of a file.

**Comment by DannyBen** [comment]
A default value is by definition, allowed.
I need an example (minimal bashly.yml and other reproduction steps, if any).

**Comment by DannyBen** [comment]
Nevermind - I see the problem.

```yaml
# bashly.yml
name: cli
help: Sample application
version: 0.1.0

args:
- name: file
  default: README.md
  validate: file_exists
```

with `bashly add validations`.

I will need to refactor the validations to run after the conversion of the command input to the `args` array.

**Comment by keilmillerjr** [comment]
Thank you for the swift response. Here's what I am working on. go-yq arch package is a dependency.

```
# bashly.yml
name: hyprmenu-power
help: Power Menu
version: 0.1.0

commands:
- name: show
  alias: d
  help: Show power menu
  default: force

  args:
  - name: config
    required: false
    help: Path to config file
    default: /usr/local/etc/hyprmenu/power.yaml
    validate: file_exists
    validate: config_format

  examples:
  - hyprmenu-power show
  - hyprmenu-power show /usr/local/etc/hyprmenu/power.yaml

```
```
# src/lib/validations/validate_config_format.yaml
validate_config_format() {
  [[ $(yq eval ".confirmation_menu.labels | length" $1) -eq 2 ]] || echo "incorrect length of confirmation menu labels in $1"

  [[ $(yq eval ".main_menu.labels | length" $1) -eq $(yq eval ".main_menu.confirmations | length" $1) \
    && $(yq eval ".main_menu.labels | length" $1) -eq $(yq eval ".main_menu.commands | length" $1) ]] \
    || echo "Unmatching length of main menu labels, confirmation and commands in $1"
}

```

```
# /usr/local/etc/hyprmenu/power.yaml
confirmation_menu:
  labels:
    -   Yes
    -   No
    - test
main_menu:
  labels:
    - ⭘  Power Off
    - ⏼  Reboot
    - ⏾  Suspend
    -   Hibernate
    -   End Session
    -   Lock Screen
  confirmations:
    - true
    - true
    - false
    - false
    - true
    - false
  commands:
    - systemctl poweroff
    - systemctl reboot
    - systemctl suspend
    - systemctl hibernate
    - hyprctl dispatch exit
    - swaylock

```

The custom validation should check and fail if the confirmation_menu labels array does not have two items. Inserted `- test` to force a failure. Both tests should fail, in my opinion. However, with a default value being applied, the validation is skipped.
```
./hyprmenu-power show
args:
- ${args[config]} = /usr/local/etc/hyprmenu/power.yaml
```
```
./hyprmenu-power show /usr/local/etc/hyprmenu/power.yaml
validation error in CONFIG:
incorrect length of confirmation menu labels in /usr/local/etc/hyprmenu/power.yaml

```
