### ISSUE TITLE
Flag arguments with a single hyphen prefix are not working

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#499]
### Bashly Version

Latest Ruby Gem

### Description

Right now, when using flag arguments (`--options ARG`) breaks when the `ARG` contains a single leading hyphen - for example: `--options '-file -compact'`

This is caused since the `normalize_input()` function splits any single hyphen followed by 2 or more characters to the individual short flags: `-file` becomes `-f -i -l -e`.

### Contents of bashly.yml

```yaml
name: cli
help: Sample application
version: 0.1.0

flags:
- long: --options
  short: -o
  arg: list
  help: Provide options
- long: --force
  short: -f
  help: Force overwrite
```

### Reproduction Steps

```bash
$ bashly g
$ ./cli -o -force
```

### Actual Behavior

This fails with the following error:

```
invalid option: -c
```

since the input was converted to `-o -f -o -r -c -e` which is then thought to be:
1. -o -f (-f becomes the arg of -o)
2. -o -r (-r becomes the arg of -o)
3. -c is then considered the first invalid option.

### Expected Behavior

The value `-force` should be assigned to `--option`:

```bash
${args[--options]} = -force
```
