### ISSUE TITLE
bash completions can't work properly when the position args used 'allowed:'

### ISSUE THREAD

**Issue by malongshuai** [DannyBen/bashly#501]
bashly Version:
```
❯ bashly --version
1.1.7
```

bashly.yml:
```yml
name: cli
help: Sample application
version: 0.1.0

commands:
  - name: completion
    help: create completion
    completions:
      - <completion>

  - name: download
    alias: d
    help: Download a file
    completions:
      - <download>
    args:
      - name: source
        help: URL to download from
        allowed: [one, two, three]
```

when i press the `<TAB>` after `./cli download`, it gives some errors:
```
❯ eval "$(./cli completion)"
❯ ./cli download <TAB>-bash: compgen: download: invalid action name
<TAB>-bash: compgen: download: invalid action name
<TAB>-bash: compgen: download: invalid action name
```

what i can do about it, thanks

**Comment by DannyBen** [comment]
There is no need to use the `completions` command in the YAML file, unless you want to add something special.
See the [Completions Example](https://github.com/DannyBen/bashly/tree/master/examples/completions#bash-completions-example).

All you need is this:

```yaml
# src/bashly.yml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: completion
  help: create completion

- name: download
  alias: d
  help: Download a file
  args:
  - name: source
    help: URL to download from
    allowed: [one, two, three]
```

then run

```bash
$ bashly generate
$ bashly add completions
````

then put this in the completion command partial file:

```bash
# src/completion_command.sh
send_completions
```

(and of course, `bashly g` again).
