### ISSUE TITLE
Repeatable args don't escape quotation marks

### ISSUE THREAD

**Issue by pcrockett** [DannyBen/bashly#503]
### Bashly Version

Latest Ruby Gem

### Description

The [advice for taking repeatable args](https://bashly.dannyb.co/configuration/argument/#repeatable) involves the use of `eval` (which is fine).

However the way repeatable args are implemented, that advice will encounter problems if a parameter contains a quotation mark.

### Contents of bashly.yml

```yaml
name: cli
help: Sample application
version: 0.1.0

commands:
- name: test

  args:
  - name: term
    required: true
    repeatable: true
```

### Reproduction Steps

contents of `test_command.sh`:

```bash
inspect_args

eval "terms=(${args[term]})"
for t in "${terms[@]}"; do
    echo "--> ${t}"
done
```

then run:

```bash
bashly generate
./cli test hello 'foo"bar'
```

### Actual Behavior

we get this output:

```plaintext
args:
- ${args[term]} = "hello" "foo"bar"
./cli: eval: line 166: unexpected EOF while looking for matching `"'
```

side note: we can also get code injection, with:

```bash
./cli test hello "foo\") && (echo 'uh oh, code injection....'\""
```

which gives us this output:

```plaintext
args:
- ${args[term]} = "hello" "foo") && (echo 'uh oh, code injection....'""
uh oh, code injection....
--> hello
--> foo
```

### Expected Behavior

```plaintext
args:
- ${args[term]} = "hello" "foo\"bar"
--> hello
--> foo"bar
```
