### ISSUE TITLE
Heredoc indentation issue in bashly generated functions.

### ISSUE THREAD

**Issue by fhacloid** [DannyBen/bashly#517]
### Bashly Version

1.1.1 (using nix as package manager)

### Description

Hi, I think I found an edge case where bashly doesn't detect heredoc properly and indent an heredoc inside a generated function.

For reference, this issue is related to [this PR](https://github.com/DannyBen/bashly/pull/496)

In my script I am using heredoc inside variables declared inline on a multiline command like this:

```bash
CY_PROJECT_NAME="${pname}" \
CY_PROJECT_DESCRIPTION="Test project" \
CY_PROJECT_CONFIG_REPOSITORY_CANONICAL="cycloid-template-catalog-config" \
CY_PROJECT_PIPELINE="$(cat <<EOF
[
  {
    "pipeline_name": "${pname}-${env}",
    "use_case": "${use_case}",
    "environment":
    {
      "canonical": "${env}",
      "cloud_provider_canonical": "google"
    }
  }
]
EOF
)" \
CY_PROJECT_INPUTS="$(cat <<EOF
[
  {
    "use_case": "${use_case}",
    "environment_canonical": "${env}",
    "vars":
    {
      "Cloud provider":
      {
        "access":
        {
          "gcp_project": "cycloid-demo",
          "gcp_zone": "europe-west1-b",
          "gcp_credentials_json": "((admin_gcp_cycloid_sandbox.json_key))"
        }
      },
      "App":
      {
        "config":
        {
          "module.myapp.instance_type": "medium"
        }
      },
      "Git":
      {
        "config":
        {
          "config_git_private_key": "((cycloid_template_catalog_ssh.ssh_key))"
        },
        "stack":
        {
          "stack_git_private_key": "((cycloid_template_catalog_ssh.ssh_key))"
        }
      }
    }
  }
]
EOF
)" \
CY_PROJECT_OWNER="admin" \
CY_PROJECT_SERVICE_CATALOG_REF="cycloid:terraform-gcp-stack-templated" \
CY_PROJECT_ORG="${ORG}" \
cy_create_project
```

My issue I think is that bashly generated code indent the heredoc:

```bash
cy_provisioner_test_command() {
  # ... Previous function code
  CY_PROJECT_NAME="${pname}" \
  CY_PROJECT_DESCRIPTION="Test project" \
  CY_PROJECT_CONFIG_REPOSITORY_CANONICAL="cycloid-template-catalog-config" \
  CY_PROJECT_PIPELINE="$(cat <<EOF
  [
    {
      "pipeline_name": "${pname}-${env}",
      "use_case": "${use_case}",
      "environment":
      {
        "canonical": "${env}",
        "cloud_provider_canonical": "google"
      }
    }
  ]
EOF
  )" \
  CY_PROJECT_INPUTS="$(cat <<EOF
  [
    {
      "use_case": "${use_case}",
      "environment_canonical": "${env}",
      "vars":
      {
        "Cloud provider":
        {
          "access":
          {
            "gcp_project": "cycloid-demo",
            "gcp_zone": "europe-west1-b",
            "gcp_credentials_json": "((admin_gcp_cycloid_sandbox.json_key))"
          }
        },
        "App":
        {
          "config":
          {
            "module.myapp.instance_type": "medium"
          }
        },
        "Git":
        {
          "config":
          {
            "config_git_private_key": "((cycloid_template_catalog_ssh.ssh_key))"
          },
          "stack":
          {
            "stack_git_private_key": "((cycloid_template_catalog_ssh.ssh_key))"
          }
        }
      }
    }
  ]
  EOF
  )" \
  CY_PROJECT_OWNER="admin" \
  CY_PROJECT_SERVICE_CATALOG_REF="cycloid:terraform-gcp-stack-templated" \
  CY_PROJECT_ORG="${ORG}" \
  cy_create_project 
  # ... rest of the function
}
```
This break my code, is there a way to fix it ? (I am using 2 spaces for indent).

I am willing to help or provide more information.

Thank you for your time. :)

### Contents of bashly.yml

```yaml
name: cy-provisioner
help: CLI to provision dev environments for cycloid internal testing
version: 0.1.0

environment_variables:
- name: CY_SOURCE_API_KEY
  help: Cycloid API key with read access to credentials
  required: true
- name: CY_SOURCE_ORG
  help: Cycloid source organization name
  default: "cycloid"
  required: true
- name: CY_SOURCE_API_URL
  help: Cycloid API URL (no trailling slash)
  default: "https://http-api.cycloid.io/api"
- name: CY_SOURCE_CREDENTIAL_CANONICAL
  help: The canonical name of the source credential for provisioning
  default: "onprem-provisioning-credentials"
  required: true
- name: CY_SOURCE_CREDENTIAL_RAW
  help: Use this variable if you want to provide directly the credential's json data.
  required: false
- name: CY_TARGET_API_KEY
  help: Cycloid API key
  required: true
- name: CY_TARGET_ORG
  help: Cycloid organization name
  required: true
- name: CY_TARGET_API_URL
  help: Cycloid API URL (no trailling slash)
  required: true
- name: CY_ONPREM_INSTANCE_IP
  help: The VM instance where cycloid is installed, required for on-prem install
  required: false
- name: ENV
  help: The current cycloid env, put your username on local machines run.
  required: true

dependencies:
  cy: "Download cycloid CLI here: https://github.com/cycloidio/cycloid-cli/releases/latest"
  curl: "Curl must be installed on your system"
  jq: "Jq must be installed on your system"
  git: "Git must be installed on your system"
  ssh-add: "ssh-add must be installed on your system"
  ssh-agent: "ssh-agent must be installed on your system"
  ssh: "ssh must be installed on your system"

flags:
- long: --verbose
  short: -v
  help: Enable debug output

commands:
- name: provision
  help: Provision a dev environment

  examples:
  - cy-provisioner provision

- name: test
```

### Reproduction Steps

Generate a script with a command using a heredoc in a multiline using this script (requires bashly ~1.1.1):

```bash
bashly init --minimal
cat <<'EOF' > src/root_command.sh
MY_VAR=${args[source]} \
MY_MULTILINE_VAR="$(cat <<EOT
mulitiline
hapiness
EOT
)" \
echo $MY_VAR $MY_MULTILINE_VAR
EOF
bashly generate
./download toto
```

### Actual Behavior
```
created src/bashly.yml
run bashly generate to create the bash script
creating user files in src
skipped src/root_command.sh (exists)
created ./download
run ./download --help to test your bash script
./download: line 237: warning: here-document at line 16 delimited by end-of-file (wanted `EOT')
./download: line 238: unexpected EOF while looking for matching `)'
```
### Expected Behavior

```
$ ./download toto
toto mulitiline
hapiness
```

expected function output:
```bash
root_command() {
  # src/root_command.sh
  MY_VAR=${args[source]} \
  MY_MULTILINE_VAR="$(cat <<EOT
mulitiline
hapiness
EOT
  )" \
  bash -c 'echo "$MY_VAR" "$MY_MULTILINE_VAR"'
}
```
