### ISSUE TITLE
The Flag value is detected as an Argument

### ISSUE THREAD

**Issue by kimyvgy** [DannyBen/bashly#521]
### Bashly Version

ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]

### Description

The `flags` doesn't work as expected. The value of Flag is detected as Argument.

### Contents of bashly.yml

```yaml
name: omf
help: omf
version: 0.1.0

commands:
- name: bootstrap
  help: Bootstrap the server
  args:
  - name: provider
    default: github
    help: Git Provider
    allowed:
    - bitbucket-server
    - git
    - gitea
    - github
    - gitlab
  flags:
  - long: --owner
    help: Git repository owner
    required: true
```

### Reproduction Steps

```bash
bashly init --minimal
bashly generate

./omf bootstrap github --owner kimyvgy
./omf bootstrap github --owner=kimyvgy
```
### Actual Behavior

```bash
invalid argument: kimyvgy
```

### Expected Behavior

```bash
# this file is located in 'src/bootstrap_command.sh'
# code for 'omf bootstrap' goes here
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[provider]} = github
- ${args[--owner]} = kimyvgy
```

**Comment by kimyvgy** [comment]
Adding `flags.arg` will fixed this issue. I think the docs should describe clearly for flags that can be assigned values, the "arg" field needs to be added to work.
```yaml
  flags:
  - long: --owner
    help: Git repository owner
    arg: owner
    required: true
```
