### ISSUE TITLE
Is it possible to have no command and take arguments from user ?

### ISSUE THREAD

**Issue by jakre1234** [DannyBen/bashly#532]
Hi Team,
So I was wondering if it's possible to have no command and only support for general flags and arguments. I have a shell script which performs an action and I want the user to pass the mode via the -m(--mode) flag.
So I have two modes supported, mute and block. Going by Bashly's general flow I can have seperate commands for both and in that case the expected command format will be:
```
./script [command] -flags
./cli mute -u username
./cli block -u username
```
but instead of having commands, I want the users to directly pass the mode via the -m flag and hence I want the below format:
```
./cli -m mute -u username
./cli -u username -m block
```

See how the user don't have to pass any command and instead directly pass via the flags.

**Comment by DannyBen** [comment]
Sure it can. 

Running `bashly init --minimal` shows an example without commands.

This bashly.yml complies with the usage pattern you provided:

```yaml
name: cli
help: Sample minimal application without commands
version: 0.1.0

flags:
- long: --mode
  short: -m
  arg: mode
  allowed: [mute, block]
  help: Mode

- long: --username
  short: -u
  arg: name
  help: User name
```

```bash
$ ./cli -m mute -u admin
# this file is located in 'src/root_command.sh'
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[--mode]} = mute
- ${args[--username]} = admin
```

If it was not clear from the documentation than we need to update the documentation. Let me know if you looked anywhere and it was unclear.
