### ISSUE TITLE
Default command is not triggered when only flags are provided

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#537]
### Bashly Version

Latest Ruby Gem

### Description

When a default command is executed without arguments, but with flags, the default command is not called.

### Contents of bashly.yml

```yaml
name: cli

commands:
- name: get
  alias: g
  help: Get something
  default: force

  args:
  - name: source
    help: Source

  flags:
  - long: --debug
    short: -d
    help: Debug
```

### Reproduction Steps

```bash
$ ./cli -d       # FAILS
$ ./cli get -d   # works
$ ./cli arg -d   # works
```

### Actual Behavior

```bash
$ ./cli -d
invalid option: -d
```

### Expected Behavior

`./cli get -d` and `./cli -d` are expected to work in the same way.

```bash
$ ./cli -d
# this file is located in 'src/get_command.sh'
# code for 'cli get' goes here
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[--debug]} = 1
```
