### ISSUE TITLE
Access default value

### ISSUE THREAD

**Issue by zeroSteiner** [DannyBen/bashly#562]
### Description

First, thanks so much for your work on bashly, it's a fantastic project.

I'm hoping to request a feature to access the default value from the YAML definition to prevent the need for repeating it in the bash code. For my use case, I have this option definition:

``` yaml
  - long: --option
    arg: option
    help: Options to add to the certificate
    repeatable: true
    validate: is_valid_signing_option
    default:
      - permit-agent-forwarding
      - permit-port-forwarding
      - permit-pty
```

When the user specifies the `--option` flag, the defaults are all removed. My use case is probably uncommon, but I'd like to maintain the array to allow the user to pass multiple keys prefixed with `permit` or `no` and they'll be merged into the result as a set of enabled options. I have all of that working, but as it is now I have to have my defaults defined both in the YAML so they can be shown to the user and in the bash code, so that if only one flag is disabled the others will still be set. Basically, I'd like to be able to merge them myself by detecting the value of `args[--option]` isn't the default like this (assuming the function named `arg_option_default` returns the default value):

```bash
options="${args[--option]}"

# Get the default value from arg_option_default
default_value=$(arg_option_default)

# Check if the string equals the default value
if [[ "$options" != "$default_value" ]]; then
    # Prepend the default value to the string if they are not equal
    options="${default_value} ${options}"
fi
```

I was thinking there would probably be other use cases for checking if a value is non-default as well but I guess an alternative solution could be a flag to allow `repeatable` options to be appended to the specified default.

**Comment by DannyBen** [comment]
What is the reason for cramming multiple options inside a single flag? Why not a separate flag for each option? Wouldn't that make it both simpler to the user and the developer?

**Comment by zeroSteiner** [comment]
I was trying to keep a degree of parity with the tool I'm wrapping and how they do it. In this case the tool is `ssh-keygen` and I'm passing the arguments for the [certificate signing.](https://man.openbsd.org/ssh-keygen#CERTIFICATES) By keeping the parity, I can just refer to the upstream documentation.

**Comment by DannyBen** [comment]
I see.

The use case is quite irregular, so I am not sure the value outweighs the introduced complexity and potential confusion.
There is probably more than one way to avoid writing these values more than once, one such option is to use a combination of `private` bashly flag and YAML aliases:

```yaml
flags:
- long: --default-option
  arg: option
  repeatable: true
  private: true
  default: &options
  - permit-agent-forwarding
  - permit-port-forwarding
  - permit-pty

- long: --option
  arg: option
  help: Options to add to the certificate
  repeatable: true
  default: *options
```

Is this acceptable?

**Comment by zeroSteiner** [comment]
Yeah, that's a clever solution. Thanks! I'll go ahead and do it that way. Feel free to close this ticket out if you'd like.

**Comment by DannyBen** [comment]
Good.

I am keeping this open, as I am still considering if there is a place for a feature that makes this more straight forward.

**Comment by DannyBen** [comment]
@zeroSteiner how do you feel about this:

```yaml
# bashly.yml
name: cli
help: Sample application
version: 0.1.0

# This is the new section
variables:
- name: default_cert_options
  value: &default_cert_options
  - permit-agent-forwarding
  - permit-port-forwarding
  - permit-pty

flags:
- long: --option
  arg: option
  repeatable: true
  default: *default_cert_options
```

which will simply add this section in the command's `run` function:

```bash
# :command.run
run() {
  declare -A args=()
  declare -A deps=()
  declare -a other_args=()
  declare -a env_var_names=()
  declare -a input=()

  # This is the new section. It will allow adding arrays, associative arrays and other simple values.
  declare -a default_cert_options=(
    "permit-agent-forwarding"
    "permit-port-forwarding"
    "permit-pty"
  )
  # end of section

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "root") root_command ;;
  esac
}
```
