### ISSUE TITLE
how to implement boolean flags

### ISSUE THREAD

**Issue by dkebler** [DannyBen/bashly#57]
....just searching for some help on bash scripting and bam....this repo comes up.  way cool.  I'm giving it a whirl instead of doing my own getopts thing.  BTW thanks for the docker container that made it easy (no need to install ruby,  gem etc)

One thing I'm not grokking is implementing boolean flags.  I saw no yaml example for such.  In getopts I just set an option without : and then can have a variable changed from null to `true` in getopts.  

I see no way to assign `true` to a variable like with flags that accept an argument.  

While I am here what about assigning a default value to a (environment) variable.

Like I have 

```
args:
- name: source
  default: $PWD
  help: source to be backed up
```

will that work?

**Comment by DannyBen** [comment]
All flags are boolean (unless they have an argument).

For example, if you have an argument called `--force`, it will be set to a truthy value (`1`) to the variable `${args[--force]}`. Otherwise, this variable will not exist, meaning it will be falsey.

And yes, environment variables will work as default values, simply because whatever you provide as a default value is passed as is in the script.

Follow this example:

1. In a new folder, run `bashly init -m` to get a sample YAML file 
2. Replace the YAML file with the content of the file below
3. Run `bashly g` to generate the bash script
4. Run `./download -f -o JSON` to see the output of your `-f` boolean flag and the default value that came from an environmen variable

```yaml
name: download
help: Minimal sample script
version: 0.1.0

args:
- name: source
  default: $PWD
  help: URL to download from

flags:
- long: --force
  short: -f
  help: Overwrite existing files

- long: --output
  short: -o
  arg: FORMAT
  help: Choose output format

examples:
- download -o JSON -f
- download /tmp
```

**Comment by dkebler** [comment]
Thanks,  Ah, I see it is using the long name as the hash key since these is no `arg:` in the yaml, and using 1 for truthy.  I guess that's all I needed to know.

I'd add what your wrote  to the readme.  Very helpful.

**Comment by dkebler** [comment]
hmmm.

hmm...


another question:

`arg | If the flag requires an argument, specify its name here.`

I expeceded bashly to use my arg: <name>  as the has key instead it used the long name.

so here it should use rhost as the key
```
flags:
- long: --host
  short: -h
  arg: rhost
  help: remote host to receive backup 
```
```
Running Backup Command
args:
- ${args[source]} = /opt/bash/shell/host/all/modules/backup
- ${args[--mirror]} = 1
- ${args[--host]} = test
```
expected - `${args[rhost]} = test`  or a variable $rhost  being set to `test`

I gues I don't see the point of arg: except to let bashly know that the flag takes an argument.  In which case it could be anything (e.g. 1)

**Comment by DannyBen** [comment]
> I expected bashly to use my arg: as the hash key instead it used the long name, or set a variable of that name.

No.

The purpose of `arg` here is only for display purposes, and it is by design not used as the variable name, for good reason.

Consider this usage pattern:

`convert --input PATH --output PATH`

If the word `path` would be used as the name, it would conflict.
The long argument is always the variable name - so in this case you will have `${args[--input]}` and `${args[--output]}`.

This is compatible in concept to all other CLI frameworks I am using, and my role model in particular, is the cross language [docopt parser](http://docopt.org/).

**Comment by DannyBen** [comment]
Oh - and just remembered one more purpose of the arg:

If you define an argument for a flag, and the user does not provide it in the command line, it will show a friendly error.

For example, given this YAML:

```yaml
name: download
help: Sample minimal application without commands
version: 0.1.0

flags:
- long: --url
  short: -u
  required: true
  arg: address
  help: URL to download from

examples:
- download -u example.com
```

If you run it without the argument, you get this:

```bash
$ ./download -u
--url requires an argument: --url, -u ADDRESS
```
