### ISSUE TITLE
Add the ability to cherry-pick disable non-essential features

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#576]
Some of the things that are generated in the final script may be unnecessary or unused in some cases.
Although setting `BASHLY_ENV=production` removes *some* of the development-oriented features, there are other features that can still be considered dead weight, as was raised in #575.

Perhaps adding a single `disable` setting that accepts an array of strings can be used to tweak these features.

These are the candidates:

#### Deps array (`disable.deps_array`)

```bash
declare -A deps=()
```

#### Header comment (`disable.header_comment`)

```bash
# This script was generated by bashly 1.2.4 (https://bashly.dannyb.co)
# Modifying it manually is not recommended
```

#### Bash3 bouncer (`disable.bash3_bouncer`)

```bash
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi
```

#### Inspect Args function (`disable.inspect_args`)

```bash
inspect_args() { ... }
```

#### View markers (`disable.view_markers`)

```bash
# :command.version_command  <-- this type of comment
version_command() { ... }
```

**Comment by dsmith4-godaddy** [comment]
I'd be hesitant to make the bash3 bouncer optional, because _someone_ is still using bash3 and this will break 🤣 

As noted in the other thread, I wouldn't make disable.deps_array the default, because I'm sure someone is using it in production. It'll be nice to have the option though.

I'm not sure if it's worth the effort to implement separate disable flags for those things that already are removed when `production` is set, but then I'm not the one doing the work. The header_comment and deps_array are ones I'll certainly use on my production scripts.

**Comment by DannyBen** [comment]
Alright. I have changed my mind about having a single `disable` option - since it is a) negative, b) harder to cherry pick and c) as you mentioned - conflicts with `env == production`.

Instead, I am adding these settings, with these default values:

```yaml
# Tweak the script output by enabling or disabling some script output.
# These options accept one of the following strings:
# - production      render this feature only when env == production
# - development     render this feature only when env == development
# - always          render this feature in any environment
# - never           do not render this feature
enable_header_comment: always
enable_bash3_bouncer: always
enable_view_markers: development
enable_inspect_args: development
enable_deps_array: always
```

This allows configuring which option is rendered in which environment, so I suspect it will be clearer and more useful for more people.

I will create a PR with these changes shortly - would you be able to test it?
