### ISSUE TITLE
respect ' ' as single literal flag argument so the argument can contain dashes

### ISSUE THREAD

**Issue by dkebler** [DannyBen/bashly#58]
Hope you don't mind me bringing up issues I have.  Maybe you haven't had much feedback.

I need to be able to pass on native flags to the underlying command (rdiff-backkup).
```
- long: --options
  short : -o
  arg: options
  help: rdiff options 
```

so trying
`./backup -o '-test -a'`

produces
`--options requires an argument: --options, -o OPTIONS`

I have a work around but it requires escaping every dash

`./test -o '\-test \-a'`

then in my script
options=$(echo ${args[--options]} | awk '{gsub(/\\/," ")}1')

gives
`rdiff-backup -test -a`

bashly should treat a single quoted argument as a single literal argument and not try to parse within it

**Comment by DannyBen** [comment]
Well,

It is not the quotes that are the issue. It is the fact this argument contains a leading dash.

Quotes (single or double) are never passed on to the script. See this bash script:

```bash
#!/usr/bin/env bash
echo "1: $1"
echo "2: $2"
echo "3: $3"
```

Running it with `./test.sh hello "-whatever -world" will just pass two arguments instead of three. No quotes will be received.

Due to the leading dash in `-whatever`, bashly thinks it is a flag and complains.

There might be a way to fix that, but it will come at a cost.
If the behavior is changed, it will mean that anything following a flag with an argument, is "consumed" as its value, even if it was meant to be another flag by mistake.

Considering this bashly config:

```yaml
flags:
- long: --options
  short: -o
  arg: list
  help: Options
- long: --force
  short: -f
  help: Force
```

Running `$ ./download -o -force`, currently displays the proper error:
`--options requires an argument: --options, -o LIST`

if the behavior is changed, it will not.

**Comment by DannyBen** [comment]
I have released a release-candidate version that should allow flag arguments to start with a dash, and should solve your use case.

Since you mentioned you are using this with docker, I have also released it to dockerhub so you can test before I release a stable version.

You can test it by adding another alias (or replacing your alias if you prefer):

```
$ alias bashlydev='docker run --rm -it --volume "$PWD:/app" dannyben/bashly:0.4.1rc1'
```

Then, using this sample YAML:

```yaml
name: download
help: Sample minimal application without commands
version: 0.1.0

flags:
- long: --force
  short: -f
  help: Overwrite existing files

- long: --options
  short: -o
  arg: list
  help: Options list
```

will allow running a command like this:

```shell
$ ./download -o '--anything -goes' -f
# this file is located in 'src/root_command.sh'
# you can edit it freely and regenerate (it will not be overwritten)
args:
- ${args[--force]} = 1
- ${args[--options]} = --anything -goes
```
