### ISSUE TITLE
Environment variable prefix and from flags

### ISSUE THREAD

**Issue by ckt114** [DannyBen/bashly#606]
### Description

Please implement a feature to create environment variable prefix and from flags.

Example:

```yaml

environment_variables_prefix: MY_CLI

environment_variables:
- name: SERVER_NAME    # will create $MY_CLI_SERVER_NAME
  

flags:
- long: --auth-token
  short: -t
  default: abc
  evar: true  # will create MY_CLI_AUTH_TOKEN=abc
```

**Comment by DannyBen** [comment]
Interesting.

I am assuming that the value provided by the CLI arguments takes higher precedence over its environment variable?

**Comment by DannyBen** [comment]
I just remembered that this kind of feature was discussed in the past, but was unable to find the exact discussion.

I also remembered that this feature is already available, in a simple (yet undocumented) way:

By simply providing a default like `default: ${API_KEY}`, you let bash itself do its thing.
You can (but don't have to) still define the environment variable properly, like I did in the below YAML, to get the extra features of validation, default value etc.

```yaml
name: cli
help: Sample application
version: 0.1.0

environment_variables:
- name: api_key
  help: Set your API key

flags:
- long: --key
  short: -k
  arg: key
  help: API key
  default: ${API_KEY}
```

As for the prefix - I am not a fan of this feature.
In your script, you will still have to use the full name of the variable - so this only adds confusion.
I prefer optimizing for READ and not for WRITE - and not having a prefix is easier to read, follow and understand.
