### ISSUE TITLE
Allow root flags to be specified after subcommands

### ISSUE THREAD

**Issue by ckt114** [DannyBen/bashly#607]
### Description

Currently, the flags that are defined for the root command can't be used after the subcommand. This is a use case considered as global flags. It does work if the root flags are specified before the subcommand. However, it's quite unintuitive.

cli/src/bashly.yml
```yaml
name: cli
version: 0.1.0

flags:
- long: --unzip
  short: -u
  default: example.com

commands:
- name: download
  args:
  - name: url
    required: true
```

```console
$ ./cli --unzip download https://example.com/file.zip  # this works

$ ./cli download https://example.com/file.zip --unzip  # throws invalid flag error
```

**Comment by DannyBen** [comment]
What you see is by design. This is what *makes* the flags global.
The way I see it, this provides a semantic, intentional CLI:

```bash
$ docker --debug images --all
```

The above can be read like "run docker with debug mode and show all images"
You are not enabling `--debug` on the images command, but on the entire `docker` command.

By the way, the actual `docker` command behaves in the same way as my interpretation of global flags: 

```bash
$ docker --debug images --all   # works
$ docker images --debug --all   # fails
unknown flag: --debug
See 'docker images --help'.
```

as well as `git`:

```bash
$ git status --git-dir PATH_TO_DIR   # fails
$ git --git-dir PATH_TO_DIR status   # works
```

You may want to search for the word "global" or other similar concepts in this repo - there are a few discussions and PRs on the subject.

If you wish to have some flags for more then one command, this does not make them global - it just makes them *shared* flags, which can be achieved by using YAML anchors ([Examples > Reusable Flags Example](https://github.com/DannyBen/bashly/tree/master/examples/reusable-flags#reusable-flags-example)).

If you require some assistance in structuring your YAML file to accomplish a certain CLI format, feel free to open a separate discussion.

**Comment by DannyBen** [comment]
By the way - if you insist on having your flags global and still available to the commands, you can also use the YAML anchors trick to achieve this without repeating yourself:

```yaml
name: docker
help: Sample application
version: 0.1.0

flags:
- &debug
  long: --debug
  short: -d
  help: Debug mode

commands:
- name: images
  alias: i
  help: List images
  flags:
  - *debug
  - long: --compact
    short: -c
    help: Compact list
```

The `--debug` flag will be available both before and after here:

```bash
$ ./docker images -dc
args:
- ${args[--compact]} = 1
- ${args[--debug]} = 1

$ ./docker -d images -c
args:
- ${args[--compact]} = 1
- ${args[--debug]} = 1
```
