### ISSUE TITLE
Improper escaping in examples and help text

### ISSUE THREAD

**Issue by ionrover2** [DannyBen/bashly#636]
### Bashly Version

Older Ruby Gem

### Description

Version 1.2.10 (via nixpkgs)

I was making a demo for my team with bashly (love it btw) and when trying to create a completions function. I defined the command in the yml and in both help and in examples fields, I tried defining a command like so `eval "$(command completions)"`

turns out when you invoke the help the output of the sub shell, in this case the output of the completions function) is printed to the screen. ideally the help and example fields should be properly escaped to prevent unintended execution.

### Contents of bashly.yml

```yaml
command:
  name: test
  help: | 
    check this out "$(top)"
  example:
    - check this out "$(top)"
```

### Reproduction Steps

try adding a subshell command to the help or example fields contents and see if it executes in the generated bashly script
