### ISSUE TITLE
[Feature] Support allowed argument values as an option

### ISSUE THREAD

**Issue by abh1kg** [DannyBen/bashly#65]
First of all, I cannot sing the praises of `bashly` enough - I have been using it heavily for a BASH CLI in my project for quite some time now and it _just works_.

One feature that I'd like to see personally is support for allowed options for arguments. For example, a suggestion for the `bashly.yml` could look like:

```
- name: login
  short: l
  help: Log on to a cool service

  args:
  - name: role
    help: Role for user
    required: true
	allowed: ["admin", "user"]
```

The behaviour I am expecting is:
:heavy_check_mark: `login admin`
:heavy_check_mark: `login user`
:x: `login anythingelse` - this could fail with an error message like `Invalid role - allowed values are "admin" and "user"`

**Comment by DannyBen** [comment]
I am happy to hear that other people make good use of bashly, thanks for sharing that.

While I can see the value of what you are proposing, my initial reaction is that this is something that is better handled by the application space, rather than the framework space.

### Why I think it should be handled by the user-domain application

Note that even in your question, you wanted to show a friendly error to the user:

> `Invalid role - allowed values are "admin" and "user"`

So, if this kind of feature is handled by the framework, it will require doing quite a few things. Such as, handle the help message accordingly, perhaps alter the usage text, add the same kind of feature to the positional arguments, and possibly more.

Also keep in mind, one of bashly's objectives is to be easy to learn, and easy to configure. I intentionally created a minimal set of tools - so much so, that some "features" were excvluded and can be opt in by calling `bashly add FEATURE`.

### How I propose to do it (without any change to bashly).

I think you can still implement what you want, with ease, and without "copy pasting" code around. You can even do so in a way that is easy to then copy the solution between your different scripts.

Here is what I suggest:

#### Step 1: Initialize a script workspace with functions lib

```shell
$ bashly init --minimal
$ bashly add lib   # this just creates a sample function in `./sec/lib`
```

#### Step 2: Update bashly.yml with a sample flag+argument

```yaml
# bashly.yml
name: login
help: Sample minimal application without commands
version: 0.1.0

args:
- name: site
  help: Site to login to

flags:
- long: --user
  short: -u
  arg: NAME
  help: "User name. Allowed: user, admin"
```  

#### Step 3: Create the `verify_user` function

```bash
# src/lib/verify_user.sh
verify_user() {
  allowed="$1"
  if [[ ! ${args[--user]} =~ $allowed ]]; then
    echo "Invalid role. Must be one of $allowed"
    exit 1
  fi
}
```

#### Step 4: Use the new user "filter" anywhere

For example, in the root command:

```bash
# src/lib/root_command.sh
verify_user "admin|user"
inspect_args
```

---

Keep in mind, I am not totally against such a feature, and while I am sure it will add value, the question is at what cost, and what does it take away in return (e.g. configuration simplicity).

How do you feel about that?

**Comment by abh1kg** [comment]
@DannyBen : Thanks for the reply. I already make use of library scripts to make this work and it does the job just fine. Since Bashly already provides this flexibility, I am fine with not bundling this into the framework if it increases complexity.

**Comment by DannyBen** [comment]
Ok - let's keep this open for now, so we can think about it a little.

If you have further details or suggestions on implementation (for example, error message configuration - needed or not?), please share.

**Comment by abh1kg** [comment]
A generic message template along the lines of `Invalid option - allowed options are ...` should be okay for me. Of course, message templating would be nice to have.

**Comment by DannyBen** [comment]
> Of course, message templating would be nice to have.

Alright. You are familiar with `bashly add strings` yes?
This lets you customize all of bashly's text output. 

So, if we implement this feature, the message will at least be customizable in the same way - although not sure it will be able to say "Invalid **role**" - since this means it must be configured in the bashly.yml.

**Comment by DannyBen** [comment]
I think we can perhaps add this functionality without any major disruption.
Will you be able to test that it fits your use case if I create a branch with it? 
Are you using the Ruby gem or the docker version?

**Comment by abh1kg** [comment]
Currently, I'm using the Rubygem version but I am fine with testing with the docker version separately as well.

**Comment by DannyBen** [comment]
Excellent. Actually its easier for both of us to test the gem directly.
I will hopefully post a branch and instructions later.

**Comment by DannyBen** [comment]
Alright - I believe it is ready for your second opinion.

To test it (either in a new empty folder, or directly in your bashly workspace):

Create this Gemfile

```ruby
# Gemfile
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "bashly", github: 'DannyBen/bashly', branch: 'add/flag-whitelist'
```

Run `bundle`, and you are ready to test.

You can use this initial `bashly.yml` if you want:

```yaml
# bashly.yml
name: login
help: Sample minimal application without commands
version: 0.1.0

args:
- name: site
  help: Site to login to

flags:
- long: --user
  short: -u
  arg: NAME
  allowed: [user, admin]
  # required: true
  default: user
  help: "User name"
```

You can see more details in the [PR notes](https://github.com/DannyBen/bashly/pull/66)
