### ISSUE TITLE
Rest flags and arguments for commands

### ISSUE THREAD

**Issue by abh1kg** [DannyBen/bashly#70]
It would be nice to somehow disable the "invalid option" validation error for certain commands which can expect arbitrary options as flags and/or arguments. I am looking to develop a CLI which performs a few specific actions but ultimately delegates to the AWS CLI. Is this somehow possible?

Currently `bashly.yml`:
```
name: mycli
help: My amazing CLI utility
version: 0.1.0

commands:
- name: aws
  help: Delegators to AWS CLI
  dependencies:
  - aws
  commands:
  - name: deploy-stack
    help: |-
      Deploys a CloudFormation stack from the provided template file.
    args:
    - name: file_path
      help: Path to a file
      required: true
    - name: stack_name
      help: Name of CloudFormation stack
      required: true
    - name: template_file_path
      help: Path to CloudFormation template
      required: true
```

Command (which I wish it works): 
```
mycli aws deploy-stack file1 mystack file2 --force-upload --s3-bucket mybucket
```

However, it exits with error:
```
invalid option: --force-upload
```

Would it be possible to relax the validation checks for a few commands?
