### ISSUE TITLE
Support for optional flag argument (`--flag [arg]`)

### ISSUE THREAD

**Issue by dkebler** [DannyBen/bashly#88]
It seems that if a flag has a default set in bashly.yml that it wil have that value whether or not the flag was set in the command line.

That was an unexpected behavior.

Is is possbile to get the behvior I want.

```
flags:
  - long: --someflag
    arg: someflag
    help:  test some flag
    default: true
```

`./,mybashly  `

I expect  `${args[--someflag]}`  to be empty but it is `true`

`./mybashly --someflg `

I expect  ${args[--someflag]}  to be `true` and it is

`./mybashly --someflg avalue`

I expect ` ${args[--someflag]}`  to be `avalue` and it is

in essence I need a flag that can act as a flag without a value when it is not is set or as one with a value if it is set.  For example I need to set a default mount point directory if --view is set but if --view /some/mountpoint is passed I need to use that value.  If the flag is not set at all I need to ignore this all together.

```
  - long: --view
    arg: mount
    help: mount snapshot for viewing at mount point ( default is <target>/view)
```
```
if [[ ${args[--view]} ]]; then 
    if [[ -e ${args[--view]} ]]; then
        $mount=${args[--view]}
    else
        $mount="${target}/view"
    fi
    cmd="sudo $password $bin -r $target mount $mount"; 
fi
```

**Comment by DannyBen** [comment]
I am sorry, I have never seen any argument act like what you want. A flag either requires an argument, or not. 

> ./,mybashly
>
> I expect ${args[--someflag]} to be empty but it is true

Why is this expected? The whole purpose of the `default` setting is to make sure this flag is **never** empty.


> ./mybashly --someflg
> 
> I expect ${args[--someflag]} to be true and it is

This is incorrect. When running with a flag that requires an argument, you will get:

`--someflag requires an argument: --someflag SOMEFLAG`


What you are trying to achieve should probably be separated to two different flags, for example:

--mount: Enable mount to the default path
--path: Change mount path (implies --mount)

**Comment by dkebler** [comment]
two args are ok given the way the default is assigned regardless of flag being set or not.

I can get close to what I want if I do it like this then either one or the other need be set but not both    

```
  - long: --view
    short: -v
    help: mount snapshot for viewing at default mount point ( default is BACKUP_MOUNT or /opt/backup/view)
  - long: --view-path
    help: set custom mount path for viewing of snapshot (--view not needed if set)
    arg: path
```

```
if [[ ${args[--view]} || ${args[--view-path]} ]]; then
    mount=${args[--view-path]:-$BACKUP_MOUNT}
    mount=${mount:-"/opt/backup/view/"}
    echo view mount point $mount
    if [[ -e ${mount} ]]; then
        cmd="$password $bin -r $target mount $mount";
        echo browse files at $mount/snapshots/latest${source}
    else
        echo $mount:  directory for mounting snapshot for viewing does not exist.  Create and try again
        return 3
    fi
fi
```

**Comment by DannyBen** [comment]
Alright.

Just a couple tips, in case they are helpful:

1. You can use the [`environment_variable`](https://bashly.dannyb.co/configuration/environment-variable/) option to define desired env vars with defaults.
2. You can probably simplify your code a little.

```yaml
# src/bashly.yml
# ...
environment_variables:
- name: backup_mount
  help: Set custom mount path for viewing of snapshot
  default: /opt/backup/view

flags:
- long: --view
  short: -v
  help: Mount snapshot for viewing at default mount point
- long: --view-path
  help: Set custom mount path for viewing of snapshot (implies --view)
  arg: path
```

```bash
# src/the_command.sh

default_view_path="$BACKUP_MOUNT"
view_path=${args[--view-path]}
view=${args[--view]:-$view_path}

if [[ $view ]]; then
  mount="${view_path:-$default_view_path}"
  echo mount: $mount
else
  echo no mount
fi
```
