### ISSUE TITLE
Flags with arguments consume other flags instead of erroring

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#89]
### Bashly config:

```yaml
name: download
version: 0.1.0

flags:
- long: --path
  arg: path
  help: path to directory
  default: somedir
- long: --other
  help: test some flag
```

### Expected behavior

```
$ ./download --path --other
--path requires an argument: --path PATH
```

### Actual behavior

```
$ ./download --path --other
args:
- ${args[--path]} = --other
```

### Notes

Implementing this will probably mean checking for the supplied flag argument, and if it starts with a hyphen (`-`), assume it is another flag and disallow it. Therefore, need to consider this downside before implementing.
